---
- hosts: master
  become: yes
  
  tasks:
  - name: Check if Kubernetes is already initialized
    stat:
      path: /etc/kubernetes/admin.conf
    register: kubeadm_init_check

  - name: Initialize Kubernetes control plane with kubeadm init
    command: >
      kubeadm init
      --pod-network-cidr=10.244.0.0/16
    when: not kubeadm_init_check.stat.exists

  - name: Create .kube directory for root user
    file:
      path: /root/.kube
      state: directory
      mode: '0755'

  - name: Copy admin.conf to root .kube/config
    copy:
      remote_src: true
      src: /etc/kubernetes/admin.conf
      dest: /root/.kube/config
      mode: '0600'

  - name: Install Flannel CNI network plugin
    command: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
    when: not kubeadm_init_check.stat.exists
  
  - name: Get the kubeadm join command from the Kubernetes control plane
    command: kubeadm token create --print-join-command
    changed_when: false
    register: kubernetes_join_command

  - name: Display join command
    debug:
      msg: "{{ kubernetes_join_command.stdout_lines[0] }}"

  - name: Copy join command to local file
    local_action:
      module: copy
      content: "{{ kubernetes_join_command.stdout_lines[0] }}"
      dest: /tmp/kubernetes_join_command
      mode: '0755'
    become: false

- hosts: worker
  become: yes

  tasks:
  - name: Check if node is already joined to cluster
    stat:
      path: /etc/kubernetes/kubelet.conf
    register: kubelet_conf_check

  - name: Copy join command from Ansible host to the worker nodes
    copy:
      src: /tmp/kubernetes_join_command
      dest: /tmp/kubernetes_join_command
      mode: '0755'
    when: not kubelet_conf_check.stat.exists

  - name: Join the Worker nodes to the cluster
    command: sh /tmp/kubernetes_join_command
    when: not kubelet_conf_check.stat.exists
    register: joined_or_not

  - name: Cleanup join command file on worker
    file:
      path: /tmp/kubernetes_join_command
      state: absent
